### ISSUE TITLE
Проверить ручку получения данных о пользователе

### ISSUE THREAD

**Issue by MariaGrom** [Studio-Yandex-Practicum/lizaalert_backend#175]
При GET запросе по адресу: 
https://api.la-testing.ru/api/v1/profile/

передаваемые данные: 
Authorization: Bearer <access_token>

падает ошибка: 
<img width="1283" alt="Снимок экрана 2023-10-06 в 18 36 30" src="https://github.com/Studio-Yandex-Practicum/lizaalert_backend/assets/102763756/bff2ab2c-b490-4d98-9352-238ce613e4f0">

**Comment by ilin-art** [comment]
Изменить данные которые будут приходить на фронт на эти:
```
{
    id: number,
    avatar: string,
    user_name: string,
    level: string, //**"Профессионал"*/
    user_occupation: string, //**"Картограф"*/
    count_pass_course: number,
    birth_date: string,
    region: string,
    nickname: string,
    phone: string,
    email: string
}
```
